version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  # kafka-setup:
  #   build:
  #     context: ./consumerSparkDatalake
  #     # dockerfile: Dockerfile
  #   command: ["/bin/bash", "/app/create_kafka_topic.sh"]
  #   depends_on:
  #     - kafka

  streamgenerator:
    build:
      context: ./streamDatageneration
      dockerfile: Dockerfile
    command: ["/bin/bash", "/app/create_kafka_topic.sh"]
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092

  # dataprocessor:
  #   build:
  #     context: ./dataProcessSpark
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - kafka
  #     - streamgenerator
  #   environment:
  #     SPARK_MASTER_URL: spark://spark-master:7077
    # command: >
    #     ./scripts/wait-for-it.sh kafka 9092 -- echo "Starting Spark Job" &&
    #     ls -l /app/target/scala-2.12/ &&
    #     /opt/spark/bin/spark-submit \
    #     --class DroneDataProcessor \
    #     --master local[*] \
    #     --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.apache.kafka:kafka-clients:3.7.0 \ 
    #     /app/target/scala-2.13/dronedataprocessor_2.13-0.1.jar
